SELECT
    PRODUCT_CODE,
    SUM(SALES_AMOUNT) * PRICE AS SALES
FROM
    PRODUCT P
    INNER JOIN OFFLINE_SALE O ON (P.PRODUCT_ID = O.PRODUCT_ID)
GROUP BY
    O.PRODUCT_ID
ORDER BY
    SUM(SALES_AMOUNT) * PRICE DESC, PRODUCT_CODE
    